#!/usr/bin/env bash

##################################################
# NOTE: Built for Linux Mint
#
# Installation (automate this later)
# 1. sudo apt install git curl
# 2. mkdir -p $HOME/.local/bin
# 3. Pull latest yadm
#    wget -O "HOME/.local/bin/yadm" https://raw.githubusercontent.com/yadm-dev/yadm/master/yadm && chmod a+x "$HOME/.local/bin/yadm"
# 4. Add yadm to PATH
#    source ~/.profile
# 5. Pull and run bootstrap (this script)
#    yadm clone --bootstrap https://github.com/triicky1/mint
# 6. Reboot
# 7. Select Gnome-flashback+i3 in login manager (GDM3)
##################################################

# Update PATH for the current script runtime
export PATH="$HOME/.local/bin:$PATH"

function init_yadm() {
    cd "$HOME"
    yadm submodule update --recursive --init
    # Hiding the README and LICENSE file
    # Reference: https://github.com/TheLocehiliosan/yadm/issues/93
    yadm gitconfig core.sparseCheckout true
    yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE.md'

    # I prefer not having a default global git config
    read -p "yadm username[Firstname Lastname]: " name
    yadm gitconfig user.name "$name"
    read -p "yadm email[email@email.com]: " email
    yadm gitconfig user.email "$email"
    echo "Can be changed later using yadm gitconfig..."
}

function update_mint() {
    sudo apt update -y
    sudo apt upgrade -y

    echo "Packages installed: $(sudo apt list --installed | wc -l)"
    echo "Disk space: "
    df -h
}

function install_official_pkgs() {
    local pkgs=(
        python3
        python3-pip        # python package manager
        python3-devel      # python developer libraries
        python3-virtualenv # python virutal environments
        python3-matplotlib # pythons matlab plot libraries
        python3-numpy
        python3-scipy
        curl            # data transfer
        firefox         # web browser
        ghostty         # terminal emulator (+++ ligatures and terminal image support)
        clangd          # LSP for c/c++ (used by coc-clangd)
        bear            # generate compile_command.json for coc
        acpi            # battery monitor
        zathura         # lightweight pdf viewer
        rclone          # setup remote vaults (Google Drive, OneDrive, Dropbox etc.)
        vlc             # media player
        deluge          # torrent client
        ffmpeg          # video converter
        openssh-server  # ssh access to this computer (look into this more)
        p7zip-full      # unzip 7z
        neovim          # the undisputed number 1 text editor
        docker          # for matlab
        tree-sitter-cli # dependency for lazyvim
        libgtk-4-dev
        libgtk4-layer-shell-dev
        libadwaita-1-dev
        gettext
        libxml12-utils
        zig

        # Haven't decided yet
        # nautilus # file explorer

        # Things that seem useful, but needs research:
        # xcwd # get current folder (used for launching terminal)
        # i3 (tiling window manager) related:
        #   fonts-font-awesome # Icons (for larger icons in i3blocks)
        #   gnome-flashback # gnome-session (to use gnome apps with i3)
        #   sysstat # used to show cpu usage i3blocks
        # Misc.
        #   zenity # custom pop-up
        #   picocom # terminal emulator (for serial port)
        #   sxiv # image viewer
        #   flameshot # screenshot tool
        #   imagemagick # resize images
    )

    sudo apt install "${pkgs[@]}" -y &&
        echo "Installed ${pkgs[@]}"
}

function install_ghostty() {
    wget https://release.files.ghostty.org/1.3.1/ghostty-1.3.1.tar.gz
    tar -xf ghostty-1.3.1.tar.gz
    cd ghostty-1.3.1/
    zig build -Doptimize=ReleaseFast
}

function install_matlab() {
    wget -O "$HOME/.local/bin/mpm" https://www.mathworks.com/mpm/glnxa64/mpm
    chmod +x "$HOME/.local/bin/mpm"
    mpm install \
        --release=R2025b \
        --destination=$HOME/.local/share/MATLAB/R2025b \
        --products MATLAB Simulink
}

function install_kicad() {
    sudo add-apt-repository ppa:kicad/kicad-6.0.11-releases
    sudo apt update
    sudo apt install --install_recommends kicad
    sudo sed 's/^/#/' /etc/apt/sources.list.d/kicad-ubuntu*.list
}

function _create_backup() {
    local dir="$1" dest="$1.bak"
    [ -d "$dir" ] && mv -f "$dir" "$dest"
    mkdir -p "$dir"
}

function _symlink_config() {
    local app="$1" this_dir=$(cd "$(dirname "$0")" && pwd)
    # Copy source to dotfiles repository
    cp -r "$this_dir/../$app" "$HOME/dotfiles/"
    # Symlink from dotfiles to .config
    ln -s "$HOME/dotfiles/$app" "$HOME/.config/$app"
}

function setup_dotfiles() {
    mkdir -p "$HOME/dotfiles"
    for app in "nvim" "tmux" "zsh" "ghostty"; do
        _create_backup "$HOME/.config/$app"
        _symlink_config "$app"
    done
    # TODO: move .gitconfig and .gitignore to dotfiles
}

function setup_antidote() {
    {
        echo 'export ZDOTDIR="$HOME/.config/zsh"'
        echo '. "$ZDOTDIR/.zshenv"'
    } >"$HOME/.zshenv"
}

# Remove unused default folders and decapitalize
function setup_home_dirs() {
    mkdir -p $HOME/dev/thirdparty $HOME/media $HOME/tmp
    mv $HOME/Desktop $HOME/desktop
    mv $HOME/Documents $HOME/documents
    mv $HOME/Downloads $HOME/downloads
    mv $HOME/Music $HOME/media/music
    mv $HOME/Pictures $HOME/media/pictures
    mv $HOME/Videos $HOME/media/videos
    rm -r $HOME/Public $HOME/Templates
}

function prompt() {
    local question_text="$1"
    local func_name="$2"
    read -p "$question_text [y/n]: " usr_input
    if [ "$usr_input" == "y" ]; then
        eval "$func_name"
    fi
}

# REVISE THIS LATER
bootstrap_mint() {
    echo "######### Installation wizard ###########"
    prompt "Init yadm" "init_yadm"
    prompt "Update Mint?" "update_mint"
    prompt "Install official packages" "install_official_pkgs"
    prompt "Install ghostty" "install_ghostty"
    prompt "Install matlab" "install_matlab"
    prompt "Install kicat" "install_kicad"
    prompt "Setup dotfiles" "setup_dotfiles"
    prompt "Setup home folders" "setup_home_dirs"
    prompt "Setup zsh/antidote" "setup_antidote"
    echo "######### WIZARD COMPLETED ###########"

    echo "NOTE: If you ran from virtual box, make sure you shutdown"
    echo "virtual box completely (not just reboot from commandline) afterwards"
    exit 0
}
